SceneType = "Debug"
LogInConsole = True
devMode = True

[Camera]
speed = 10
acc = 3

[Screen]
screen_width = 1600
screen_height = 1000
grid = 10

[Clock]
fps = 60
renderfps = 240
gameTimer = 0
totalTicks = 0